### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Joe-Mobarak** [HusseinYoussef/Arabic-OCR#3]
Hey man 
I want to ask you a few questions 
Do you have a skype account or anything like that where i can message you 
I willl not take a lot of your time
Thanks in advance

**Comment by Joe-Mobarak** [comment]
Or you can reply me here but those are questions not issues :
My first question is regarding the line segmentation :
I didn't what quite get what is happening here :

def projection_segmentation(clean_img, axis, cut=3):
    
    segments = []
    start = -1
    cnt = 0

    projection_bins = projection(clean_img, axis)
    for idx, projection_bin in enumerate(projection_bins):

        if projection_bin != 0:
            cnt = 0
        if projection_bin != 0 and start == -1:
            start = idx
        if projection_bin == 0 and start != -1:
            cnt += 1
            if cnt >= cut:
                if axis == 'horizontal':
                    segments.append(clean_img[max(start-1, 0):idx, :])
                elif axis == 'vertical':
                    segments.append(clean_img[:, max(start-1, 0):idx])
                cnt = 0

                start = -1
    return segments

Why is cut predefined ?
Is there any IEEE paper where this algorithm is taken from ?

**Comment by HusseinYoussef** [comment]
Unfortunately, I don't have a skype account. Feel free to message me on linkedin or here.
My linkedin: https://www.linkedin.com/in/hussein-youssef-8539b0129/

I used horizontal projection method for line segmentation. Horizontal and vertical projection is a popular method for line and word segmentation. You can check the papers in the references section in the README.md file or you can google it since it's a pretty simple algorithm.

The "cut" was predefined because we were dealing with dataset with the same font so the space between lines is kinda constant so the cut variable represents the white space between lines.
