### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by beyond2013** [HusseinYoussef/Arabic-OCR#8]
Operating System: Windows 10 - 64 bit
Python 3.7
after installing requirements.txt 
when I run python OCR.py I get the error as mentioned in the subject: ValueError: too many values to unpack (expected 2)
![pythoneror](https://user-images.githubusercontent.com/4710249/94662429-ce9afd00-0321-11eb-8c21-52d442cf36ce.png)

**Comment by HusseinYoussef** [comment]
What OpenCV version are you using?
It is an issue with OpenCV version since the behavior is different across different versions of OpenCV (OpenCV2, 3, 4). I am using OpenCV4.
I think you had an older version already so it skipped installing OpenCV.
I have modified the `requirements.txt` to specify the version I was using (version 4.1.1.26) so please install again and let me know.
